PICOWARE_BOARDS_MOD_DIR := $(USERMOD_DIR)

SRC_USERMOD += $(PICOWARE_BOARDS_MOD_DIR)/picoware_boards.c

CFLAGS_USERMOD += -I$(PICOWARE_BOARDS_MOD_DIR)
CFLAGS_USERMOD += -I$(PICOWARE_BOARDS_MOD_DIR)/../lcd
