#pragma once
namespace Picoware
{
#define BUTTON_NONE -1
#define BUTTON_UART -2
#define BUTTON_PICO_CALC -3
// Directional buttons
#define BUTTON_UP 0
#define BUTTON_DOWN 1
#define BUTTON_LEFT 2
#define BUTTON_RIGHT 3
#define BUTTON_CENTER 4
#define BUTTON_OK 4
#define BUTTON_BACK 5
#define BUTTON_START 6
// Alphabet A-Z
#define BUTTON_A 7
#define BUTTON_B 8
#define BUTTON_C 9
#define BUTTON_D 10
#define BUTTON_E 11
#define BUTTON_F 12
#define BUTTON_G 13
#define BUTTON_H 14
#define BUTTON_I 15
#define BUTTON_J 16
#define BUTTON_K 17
#define BUTTON_L 18
#define BUTTON_M 19
#define BUTTON_N 20
#define BUTTON_O 21
#define BUTTON_P 22
#define BUTTON_Q 23
#define BUTTON_R 24
#define BUTTON_S 25
#define BUTTON_T 26
#define BUTTON_U 27
#define BUTTON_V 28
#define BUTTON_W 29
#define BUTTON_X 30
#define BUTTON_Y 31
#define BUTTON_Z 32
// Numbers 0-9
#define BUTTON_0 33
#define BUTTON_1 34
#define BUTTON_2 35
#define BUTTON_3 36
#define BUTTON_4 37
#define BUTTON_5 38
#define BUTTON_6 39
#define BUTTON_7 40
#define BUTTON_8 41
#define BUTTON_9 42
// Special characters
#define BUTTON_SPACE 43
#define BUTTON_EXCLAMATION 44
#define BUTTON_AT 45
#define BUTTON_HASH 46
#define BUTTON_DOLLAR 47
#define BUTTON_PERCENT 48
#define BUTTON_CARET 49
#define BUTTON_AMPERSAND 50
#define BUTTON_ASTERISK 51
#define BUTTON_LEFT_PARENTHESIS 52
#define BUTTON_RIGHT_PARENTHESIS 53
#define BUTTON_MINUS 54
#define BUTTON_UNDERSCORE 55
#define BUTTON_PLUS 56
#define BUTTON_EQUAL 57
#define BUTTON_LEFT_BRACKET 58
#define BUTTON_RIGHT_BRACKET 59
#define BUTTON_LEFT_BRACE 60
#define BUTTON_RIGHT_BRACE 61
#define BUTTON_SEMICOLON 62
#define BUTTON_COLON 63
#define BUTTON_SINGLE_QUOTE 64
#define BUTTON_DOUBLE_QUOTE 65
#define BUTTON_COMMA 66
#define BUTTON_PERIOD 67
#define BUTTON_SLASH 68
#define BUTTON_BACKSLASH 69
#define BUTTON_LESS_THAN 70
#define BUTTON_GREATER_THAN 71
#define BUTTON_QUESTION 72
#define BUTTON_BACKSPACE 73
#define BUTTON_ENTER 74
// HW504 Joystick
#define HW_LEFT_BUTTON 0
#define HW_RIGHT_BUTTON 1
#define HW_UP_BUTTON 2
#define HW_DOWN_BUTTON 3
#define HW_CENTER_BUTTON 4
// HW504 Joystick Orientation
#define HW_ORIENTATION_NORMAL 0
#define HW_ORIENTATION_90 1
#define HW_ORIENTATION_180 2
#define HW_ORIENTATION_270 3
}