#pragma once

#include "driver/gpio.h"
#include "driver/i2c_master.h"
#include "driver/spi_master.h"

#define WATCH_LCD_HOST SPI2_HOST
#define WATCH_LCD_SCLK_GPIO GPIO_NUM_7
#define WATCH_LCD_MOSI_GPIO GPIO_NUM_8
#define WATCH_LCD_CS_GPIO GPIO_NUM_9
#define WATCH_LCD_DC_GPIO GPIO_NUM_10
#define WATCH_LCD_RST_GPIO GPIO_NUM_6
#define WATCH_LCD_BL_GPIO GPIO_NUM_13
#define WATCH_LCD_EN_GPIO GPIO_NUM_40
#define WATCH_PERIPHERAL_POWER_GPIO GPIO_NUM_47

#define WATCH_TOUCH_I2C_PORT I2C_NUM_0
#define WATCH_TOUCH_SDA_GPIO GPIO_NUM_4
#define WATCH_TOUCH_SCL_GPIO GPIO_NUM_3
#define WATCH_TOUCH_RST_GPIO GPIO_NUM_5
#define WATCH_TOUCH_INT_GPIO GPIO_NUM_2
#define WATCH_TOUCH_I2C_ADDRESS 0x63
#define WATCH_TOUCH_WIDTH 240
#define WATCH_TOUCH_HEIGHT 296

#define WATCH_I2C_FREQUENCY_HZ 400000

#define WATCH_BATTERY_ADC_UNIT ADC_UNIT_1
#define WATCH_BATTERY_ADC_CHANNEL ADC_CHANNEL_0
#define WATCH_BATTERY_CHARGE_GPIO GPIO_NUM_15
#define WATCH_BATTERY_DIVIDER 0.578f
