add_compile_definitions(CROWPANEL_WATCH_2_01 ESP32)
list(APPEND MICROPY_DEF_BOARD CROWPANEL_WATCH_2_01)
set(ESP32 TRUE)

include(${CMAKE_CURRENT_LIST_DIR}/lcd/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/battery/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/touch/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/storage/micropython.cmake)

include_directories(${CMAKE_CURRENT_LIST_DIR}/../../JPEGDEC/src)

include(${CMAKE_CURRENT_LIST_DIR}/../../auto_complete/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../c/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../engine/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../font/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../jpeg/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../jsmn/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../lcd/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../log/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../mjs/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../mmbasic/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../picoware_boards/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../response/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../textbox/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../usb_video/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../vector/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../video/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../vt/micropython.cmake)

include(${CMAKE_CURRENT_LIST_DIR}/../../http/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../websocket/micropython.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../../ghouls/micropython.cmake)
