#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "Elecrow CrowPanel Watch 2.01"
#endif

#define MICROPY_HW_MCU_NAME "ESP32-S3"
#define MICROPY_BOARD_FROZEN_BOOT_FILE "picoware_boot.py"
#define MICROPY_PY_NETWORK (1)
#define MICROPY_PY_NETWORK_WLAN (1)
#define MICROPY_PY_BLUETOOTH (1)
#define MICROPY_HW_ENABLE_UART_REPL (1)
#define MICROPY_HW_USB_CDC_DTR_RTS_BOOTLOADER (0)
#define MICROPY_HW_USB_CDC_1200BPS_TOUCH (0)

#define MICROPY_HW_I2C0_SCL (3)
#define MICROPY_HW_I2C0_SDA (4)

#define MICROPY_TASK_STACK_SIZE (16 * 1024)
#define MICROPY_THREAD_STACK_SIZE (8 * 1024)
#define MICROPY_GC_INITIAL_HEAP_SIZE (128 * 1024)
