FLIPPER_INPUT_MOD_DIR := $(USERMOD_DIR)/input

SRC_USERMOD += $(FLIPPER_INPUT_MOD_DIR)/input.c
SRC_USERMOD += $(FLIPPER_INPUT_MOD_DIR)/input_mp.c

CFLAGS_USERMOD += -I$(FLIPPER_INPUT_MOD_DIR)
CFLAGS_USERMOD += -I$(USERMOD_DIR)
CFLAGS_USERMOD += -DFLIPPER_ZERO
