#ifndef MBS_LEXER_H
#define MBS_LEXER_H

#include "mbs_util.h"

#ifdef __cplusplus
extern "C"
{
#endif

    typedef enum
    {
        T_NUMBER,
        T_STRING,
        T_IDENTIFIER,
        T_AUTO,
        T_CONT,
        T_DELETE,
        T_EDIT,
        T_FILES,
        T_LIST,
        T_LLIST,
        T_LOAD,
        T_MERGE,
        T_NEW,
        T_RENUM,
        T_RUN,
        T_SAVE,
        T_AS,
        T_CLOSE,
        T_FIELD,
        T_GET,
        T_INPUT,
        T_KILL,
        T_LINE_INPUT,
        T_LSET,
        T_MKDIR,
        T_CHDIR,
        T_NAME,
        T_OPEN,
        T_OUTPUT,
        T_PUT,
        T_RESET,
        T_RSET,
        T_ALL,
        T_CALL,
        T_CHAIN,
        T_ELSE,
        T_END,
        T_FOR,
        T_FONT,
        T_GOSUB,
        T_GOTO,
        T_IF,
        T_NEXT,
        T_ON,
        T_RESUME,
        T_RETURN,
        T_STEP,
        T_STOP,
        T_SYSTEM,
        T_THEN,
        T_TO,
        T_WHILE,
        T_WEND,
        T_CLEAR,
        T_DATA,
        T_DEF,
        T_DEFINT,
        T_DEFSNG,
        T_DEFDBL,
        T_DEFSTR,
        T_DIM,
        T_ERASE,
        T_FN,
        T_LET,
        T_OPTION,
        T_BASE,
        T_READ,
        T_RESTORE,
        T_PRINT,
        T_LPRINT,
        T_WRITE,
        T_CLS,
        T_COMMON,
        T_ERROR,
        T_SUB,
        T_LOCAL,
        T_CONST,
        T_ELSEIF,
        T_SELECT,
        T_CASE,
        T_EXIT,
        T_DO,
        T_LOOP,
        T_UNTIL,
        T_DEFAULT,
        T_ANGLE,
        T_RADIANS,
        T_DEGREES,
        T_EXPLICIT,
        T_ENDIF,
        T_ENDSELECT,
        T_ENDSUB,
        T_FUNCTION,
        T_ENDFUNCTION,
        T_PLAY,
        T_PAUSE,
        T_TURTLE,
        T_FRAMEBUFFER,
        T_LAYER,
        T_CREATE,
        T_COPY,
        T_IMAGE,
        T_PIXEL,
        T_BOX,
        T_CIRCLE,
        T_POLYGON,
        T_COLOR,
        T_TEXT,
        T_RGB,
        T_CHOICE,
        T_PI,
        T_AT,
        T_ATAN2,
        T_SHR,
        T_SHL,
        T_ERR,
        T_ERL,
        T_FRE,
        T_HELP,
        T_OUT,
        T_POKE,
        T_RANDOMIZE,
        T_REM,
        T_REMARK,
        T_SORT,
        T_SWAP,
        T_TRON,
        T_TROFF,
        T_USING,
        T_WAIT,
        T_WIDTH,
        T_PLUS,
        T_MINUS,
        T_PLUS_EQUAL,
        T_MINUS_EQUAL,
        T_MULTIPLY,
        T_DIVIDE,
        T_POWER,
        T_BACKSLASH,
        T_AMPERSAND,
        T_MOD,
        T_EQUAL,
        T_NOT_EQUAL,
        T_LESS_THAN,
        T_GREATER_THAN,
        T_LESS_EQUAL,
        T_GREATER_EQUAL,
        T_NOT,
        T_AND,
        T_OR,
        T_XOR,
        T_EQV,
        T_IMP,
        T_ABS,
        T_ATN,
        T_CDBL,
        T_CINT,
        T_COS,
        T_CSNG,
        T_CVD,
        T_CVI,
        T_CVS,
        T_EXP,
        T_FIX,
        T_INT,
        T_LOG,
        T_RND,
        T_SGN,
        T_SIN,
        T_SQR,
        T_TAN,
        T_ASC,
        T_CHR,
        T_EVAL,
        T_HEX,
        T_INKEY,
        T_INPUT_FUNC,
        T_INSTR,
        T_LEFT,
        T_LEN,
        T_MID,
        T_MKD,
        T_MKI,
        T_MKS,
        T_OCT,
        T_RIGHT,
        T_SPACE,
        T_STR,
        T_STRING_FUNC,
        T_TIME,
        T_VAL,
        T_EOF_FUNC,
        T_INP,
        T_LOC,
        T_LOF,
        T_PEEK,
        T_POS,
        T_SPC,
        T_TAB,
        T_USR,
        T_VARPTR,
        T_LPAREN,
        T_RPAREN,
        T_COMMA,
        T_SEMICOLON,
        T_COLON,
        T_HASH,
        T_NEWLINE,
        T_LINE_NUMBER,
        T_EOF,
        T_QUESTION,
        T_APOSTROPHE,
        T_COUNT
    } mbs_tok_type;

    typedef struct mbs_token
    {
        uint8_t type;
        int line, col;
        mbs_val value;   // NUMBER/STRING/IDENTIFIER (lowercased)
        mbs_str literal; // raw NUMBER text (suffix included)
    } mbs_token;

    typedef struct mbs_lexer mbs_lexer;

    const char *mbs_tok_name(uint8_t type);
    mbs_lexer *mbs_lexer_new(const char *source, int len);
    void mbs_lexer_free(mbs_lexer *lx);
    mbs_ptrarr *mbs_lexer_tokenize(mbs_lexer *lx, mbs_error *err); // mbs_token*

#ifdef __cplusplus
}
#endif

#endif // MBS_LEXER_H
