"""Explicit built-in entry points eligible for restart (no saved sessions)."""

BUILTIN_APPS = {
    'applications.FlipSocial': 'picoware.applications.applications.FlipSocial',
    'applications.agent': 'picoware.applications.applications.agent',
    'applications.app_store': 'picoware.applications.applications.app_store',
    'applications.c': 'picoware.applications.applications.c',
    'applications.games.gameboy': 'picoware.applications.applications.games.gameboy',
    'applications.games.ghouls': 'picoware.applications.applications.games.ghouls',
    'applications.javascript': 'picoware.applications.applications.javascript',
    'applications.mmbasic': 'picoware.applications.applications.mmbasic',
    'bluetooth.advertise': 'picoware.applications.bluetooth.advertise',
    'bluetooth.beacon': 'picoware.applications.bluetooth.beacon',
    'bluetooth.pair': 'picoware.applications.bluetooth.pair',
    'bluetooth.rssi_monitor': 'picoware.applications.bluetooth.rssi_monitor',
    'bluetooth.scan': 'picoware.applications.bluetooth.scan',
    'bluetooth.uart_chat': 'picoware.applications.bluetooth.uart_chat',
    'ir': 'picoware.applications.ir',
    'usb.keyboard': 'picoware.applications.usb.keyboard',
    'usb.media_keys': 'picoware.applications.usb.media_keys',
    'usb.numpad': 'picoware.applications.usb.numpad',
    'usb.payload': 'picoware.applications.usb.payload',
    'utilities.email': 'picoware.applications.utilities.email',
    'utilities.espflasher': 'picoware.applications.utilities.espflasher',
    'utilities.file_manager': 'picoware.applications.utilities.file_manager',
    'utilities.pico_ide': 'picoware.applications.utilities.pico_ide',
    'utilities.repl': 'picoware.applications.utilities.repl',
    'utilities.serial': 'picoware.applications.utilities.serial',
    'utilities.ssh': 'picoware.applications.utilities.ssh',
    'wifi.connect': 'picoware.applications.wifi.connect',
    'wifi.rssi_monitor': 'picoware.applications.wifi.rssi_monitor',
    'wifi.scan': 'picoware.applications.wifi.scan',
    'wifi.server': 'picoware.applications.wifi.server',
}
