PICOWARE_MICROPYTHON_DIR := $(USERMOD_DIR)/../../..
AUTO_COMPLETE_MOD_DIR := $(PICOWARE_MICROPYTHON_DIR)/auto_complete

SRC_USERMOD += $(USERMOD_DIR)/auto_complete.c
SRC_USERMOD += $(USERMOD_DIR)/auto_complete_mp.c

CFLAGS_USERMOD += -I$(AUTO_COMPLETE_MOD_DIR)
