#pragma once

#include "driver/gpio.h"

// LCD (ST7789V2)
#define CARDPUTER_LCD_HOST SPI2_HOST
#define CARDPUTER_LCD_BL_GPIO GPIO_NUM_38
#define CARDPUTER_LCD_RST_GPIO GPIO_NUM_33
#define CARDPUTER_LCD_DC_GPIO GPIO_NUM_34
#define CARDPUTER_LCD_MOSI_GPIO GPIO_NUM_35
#define CARDPUTER_LCD_SCLK_GPIO GPIO_NUM_36
#define CARDPUTER_LCD_CS_GPIO GPIO_NUM_37

// Keyboard + internal peripherals I2C bus
#define CARDPUTER_I2C_PORT I2C_NUM_0
#define CARDPUTER_I2C_SDA_GPIO GPIO_NUM_8
#define CARDPUTER_I2C_SCL_GPIO GPIO_NUM_9
#define CARDPUTER_I2C_FREQ_HZ 400000

// Keyboard (TCA8418)
#define CARDPUTER_KEYBOARD_I2C_ADDR 0x34
#define CARDPUTER_KEYBOARD_INT_GPIO GPIO_NUM_11

// Audio codec (ES8311)
#define CARDPUTER_AUDIO_I2C_ADDR 0x18

// I2S pins for codec link
#define CARDPUTER_I2S_BCLK_GPIO GPIO_NUM_41
#define CARDPUTER_I2S_DIN_GPIO GPIO_NUM_46
#define CARDPUTER_I2S_WS_GPIO GPIO_NUM_43
#define CARDPUTER_I2S_DOUT_GPIO GPIO_NUM_42

// SD card (SDSPI)
#define CARDPUTER_SD_HOST SPI3_HOST
#define CARDPUTER_SD_CS_GPIO GPIO_NUM_12
#define CARDPUTER_SD_MOSI_GPIO GPIO_NUM_14
#define CARDPUTER_SD_SCLK_GPIO GPIO_NUM_40
#define CARDPUTER_SD_MISO_GPIO GPIO_NUM_39

// IMU (BMI270)
#define CARDPUTER_IMU_I2C_ADDR_PRIMARY 0x68
#define CARDPUTER_IMU_I2C_ADDR_ALT 0x69

// Battery ADC
#define CARDPUTER_BATTERY_ADC_UNIT ADC_UNIT_1
#define CARDPUTER_BATTERY_ADC_CHANNEL ADC_CHANNEL_9

// IR output
#define CARDPUTER_IR_TX_GPIO GPIO_NUM_44
