#pragma once

#if defined(PICOCALC)
#define LCD_INCLUDE "../PicoCalc/picoware_lcd/picoware_lcd.h"
#define LCD_MP_INIT picocalc_lcd_init
#define LCD_MP_DEINIT lcd_deinit
#define LCD_MP_WIDTH DISPLAY_WIDTH
#define LCD_MP_HEIGHT DISPLAY_HEIGHT
#define LCD_MP_CHAR lcd_draw_char
#define LCD_MP_CIRCLE lcd_draw_circle
#define LCD_MP_CLEAR lcd_fill
#define LCD_MP_FILL_CIRCLE lcd_fill_circle
#define LCD_MP_FILL_RECTANGLE lcd_fill_rect
#define LCD_MP_FILL_ROUND_RECTANGLE lcd_fill_round_rectangle
#define LCD_MP_FILL_TRIANGLE lcd_fill_triangle
#define LCD_MP_BLIT picocalc_lcd_blit
#define LCD_MP_LINE lcd_draw_line
#define LCD_MP_PIXEL lcd_draw_pixel
#define LCD_MP_RECTANGLE lcd_draw_rect
#define LCD_MP_SWAP lcd_swap
#define LCD_MP_TEXT lcd_draw_text
#define LCD_MP_TRIANGLE lcd_draw_triangle
#elif defined(WAVESHARE_1_28)
#define LCD_INCLUDE "../Waveshare/RP2350-Touch-LCD-1.28/waveshare_lcd/lcd.h"
#define LCD_MP_INIT lcd_init
#define LCD_MP_DEINIT lcd_reset
#define LCD_MP_WIDTH LCD_WIDTH
#define LCD_MP_HEIGHT LCD_HEIGHT
#define LCD_MP_CHAR lcd_draw_char
#define LCD_MP_CIRCLE lcd_draw_circle
#define LCD_MP_CLEAR lcd_fill
#define LCD_MP_FILL_CIRCLE lcd_fill_circle
#define LCD_MP_FILL_RECTANGLE lcd_fill_rect
#define LCD_MP_FILL_ROUND_RECTANGLE lcd_fill_round_rectangle
#define LCD_MP_FILL_TRIANGLE lcd_fill_triangle
#define LCD_MP_BLIT lcd_blit
#define LCD_MP_LINE lcd_draw_line
#define LCD_MP_PIXEL lcd_draw_pixel
#define LCD_MP_RECTANGLE lcd_draw_rect
#define LCD_MP_SWAP lcd_swap
#define LCD_MP_TEXT lcd_draw_text
#define LCD_MP_TRIANGLE lcd_draw_triangle
#elif defined(WAVESHARE_1_43)
#define LCD_INCLUDE "../Waveshare/RP2350-Touch-LCD-1.43/waveshare_lcd/lcd.h"
#define LCD_MP_INIT lcd_init
#define LCD_MP_DEINIT lcd_reset
#define LCD_MP_WIDTH LCD_WIDTH
#define LCD_MP_HEIGHT LCD_HEIGHT
#define LCD_MP_CHAR lcd_draw_char
#define LCD_MP_CIRCLE lcd_draw_circle
#define LCD_MP_CLEAR lcd_fill
#define LCD_MP_FILL_CIRCLE lcd_fill_circle
#define LCD_MP_FILL_RECTANGLE lcd_fill_rect
#define LCD_MP_FILL_ROUND_RECTANGLE lcd_fill_round_rectangle
#define LCD_MP_FILL_TRIANGLE lcd_fill_triangle
#define LCD_MP_BLIT lcd_blit
#define LCD_MP_LINE lcd_draw_line
#define LCD_MP_PIXEL lcd_draw_pixel
#define LCD_MP_RECTANGLE lcd_draw_rect
#define LCD_MP_SWAP lcd_swap
#define LCD_MP_TEXT lcd_draw_text
#define LCD_MP_TRIANGLE lcd_draw_triangle
#elif defined(WAVESHARE_3_49)
#define LCD_INCLUDE "../Waveshare/RP2350-Touch-LCD-3.49/waveshare_lcd/lcd.h"
#define LCD_MP_INIT lcd_init
// #define LCD_MP_DEINIT
#define LCD_MP_WIDTH LCD_WIDTH
#define LCD_MP_HEIGHT LCD_HEIGHT
#define LCD_MP_CHAR lcd_draw_char
#define LCD_MP_CIRCLE lcd_draw_circle
#define LCD_MP_CLEAR lcd_fill
#define LCD_MP_FILL_CIRCLE lcd_fill_circle
#define LCD_MP_FILL_RECTANGLE lcd_fill_rect
#define LCD_MP_FILL_ROUND_RECTANGLE lcd_fill_round_rectangle
#define LCD_MP_FILL_TRIANGLE lcd_fill_triangle
#define LCD_MP_BLIT lcd_blit
#define LCD_MP_LINE lcd_draw_line
#define LCD_MP_PIXEL lcd_draw_pixel
#define LCD_MP_RECTANGLE lcd_draw_rect
#define LCD_MP_SWAP lcd_swap
#define LCD_MP_TEXT lcd_draw_text
#define LCD_MP_TRIANGLE lcd_draw_triangle
#endif