// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// audio_pwm //
// --------- //

#define audio_pwm_wrap_target 0
#define audio_pwm_wrap 6
#define audio_pwm_pio_version 1

static const uint16_t audio_pwm_program_instructions[] = {
            //     .wrap_target
    0x9080, //  0: pull   noblock         side 0
    0xa027, //  1: mov    x, osr
    0xa046, //  2: mov    y, isr
    0x00a5, //  3: jmp    x != y, 5
    0x1806, //  4: jmp    6               side 1
    0xa042, //  5: nop
    0x0083, //  6: jmp    y--, 3
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program audio_pwm_program = {
    .instructions = audio_pwm_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = audio_pwm_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config audio_pwm_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_pwm_wrap_target, offset + audio_pwm_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

static inline void audio_pwm_program_init(PIO pio, uint sm, uint offset, uint pin) {
   pio_gpio_init(pio, pin);
   pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
   pio_sm_config c = audio_pwm_program_get_default_config(offset);
   sm_config_set_sideset_pins(&c, pin);
   pio_sm_init(pio, sm, offset, &c);
}
static inline bool audio_pwm_is_not_silence(uint16_t frequency) {
    // Check if the frequency is zero or silence
    return (frequency >= 100 && frequency <= 2000);
}
// Write `period` to the input shift register
static inline void audio_pwm_set_frequency(PIO pio, uint sm, uint32_t frequency) {
    // This sets the frequence of the tone, we will keep it like this.
    pio_sm_set_enabled(pio, sm, false);
    if (audio_pwm_is_not_silence(frequency)) {
        int period = clock_get_hz(clk_sys) / (frequency * 3);
        pio_sm_put_blocking(pio, sm, period & ~1);
        pio_sm_exec(pio, sm, pio_encode_pull(false, false));
        pio_sm_exec(pio, sm, pio_encode_out(pio_isr, 32));
        pio_sm_set_enabled(pio, sm, true);
        pio_sm_put_blocking(pio, sm, period >> 1);
    }
}

#endif

