#pragma once

#include <stdint.h>
#include <stdbool.h>

/* Display 128x64 SPI */
#define FLIPPER_LCD_WIDTH 128
#define FLIPPER_LCD_HEIGHT 64

#define FLIPPER_LCD_SCK_GPIO GPIOD
#define FLIPPER_LCD_SCK_PIN GPIO_PIN_1
#define FLIPPER_LCD_MOSI_GPIO GPIOB
#define FLIPPER_LCD_MOSI_PIN GPIO_PIN_15
#define FLIPPER_LCD_MISO_GPIO GPIOC
#define FLIPPER_LCD_MISO_PIN GPIO_PIN_2
#define FLIPPER_LCD_CS_GPIO GPIOC
#define FLIPPER_LCD_CS_PIN GPIO_PIN_11
#define FLIPPER_LCD_DC_GPIO GPIOB
#define FLIPPER_LCD_DC_PIN GPIO_PIN_1
#define FLIPPER_LCD_RST_GPIO GPIOB
#define FLIPPER_LCD_RST_PIN GPIO_PIN_0

/* SD card SPI */
#define FLIPPER_SD_CS_GPIO GPIOC
#define FLIPPER_SD_CS_PIN GPIO_PIN_12
#define FLIPPER_SD_CD_GPIO GPIOC
#define FLIPPER_SD_CD_PIN GPIO_PIN_10

/* Buttons */
#define FLIPPER_BTN_UP_GPIO GPIOB
#define FLIPPER_BTN_UP_PIN GPIO_PIN_10
#define FLIPPER_BTN_DOWN_GPIO GPIOC
#define FLIPPER_BTN_DOWN_PIN GPIO_PIN_6
#define FLIPPER_BTN_RIGHT_GPIO GPIOB
#define FLIPPER_BTN_RIGHT_PIN GPIO_PIN_12
#define FLIPPER_BTN_LEFT_GPIO GPIOB
#define FLIPPER_BTN_LEFT_PIN GPIO_PIN_11
#define FLIPPER_BTN_OK_GPIO GPIOH
#define FLIPPER_BTN_OK_PIN GPIO_PIN_3
#define FLIPPER_BTN_BACK_GPIO GPIOC
#define FLIPPER_BTN_BACK_PIN GPIO_PIN_13

/* Periph power PA3 */
#define FLIPPER_PERIPH_POWER_GPIO GPIOA
#define FLIPPER_PERIPH_POWER_PIN GPIO_PIN_3

/* I2C backlight */
#define FLIPPER_I2C_SCL_GPIO GPIOA
#define FLIPPER_I2C_SCL_PIN GPIO_PIN_9
#define FLIPPER_I2C_SDA_GPIO GPIOA
#define FLIPPER_I2C_SDA_PIN GPIO_PIN_10

/* LP5562 registers */
#define LP5562_I2C_ADDR (0x30 << 1)
#define LP5562_REG_ENABLE 0x00
#define LP5562_REG_OP_MODE 0x01
#define LP5562_REG_CONFIG 0x08
#define LP5562_REG_RESET 0x0D
#define LP5562_REG_W_CURRENT 0x0F
#define LP5562_REG_W_PWM 0x0E
#define LP5562_REG_LED_MAP 0x70
