FLIPPER_SD_MOD_DIR := $(USERMOD_DIR)/sd

SRC_USERMOD += $(FLIPPER_SD_MOD_DIR)/sd.c
SRC_USERMOD += $(FLIPPER_SD_MOD_DIR)/storage.c
SRC_USERMOD += $(FLIPPER_SD_MOD_DIR)/sd_mp.c
SRC_USERMOD += $(FLIPPER_SD_MOD_DIR)/flipper_sd_blockdev.c

CFLAGS_USERMOD += -I$(FLIPPER_SD_MOD_DIR)
CFLAGS_USERMOD += -I$(USERMOD_DIR)
CFLAGS_USERMOD += -DFLIPPER_ZERO
