#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "Waveshare ESP32-C6-Touch-AMOLED-2.06"
#endif

#define MICROPY_HW_MCU_NAME "ESP32-C6"

#define MICROPY_HW_ENABLE_UART_REPL (1)

#define MICROPY_HW_USB_CDC_DTR_RTS_BOOTLOADER (0)
#define MICROPY_HW_USB_CDC_1200BPS_TOUCH (0)

#define MICROPY_HW_I2C0_SCL (7)
#define MICROPY_HW_I2C0_SDA (8)

#define MICROPY_TASK_STACK_SIZE (16 * 1024)
#define MICROPY_THREAD_STACK_SIZE (8 * 1024)
#define MICROPY_GC_INITIAL_HEAP_SIZE (64 * 1024)