#pragma once

#include "driver/gpio.h"

// LCD (CO5300)
#define WATCH_LCD_HOST SPI2_HOST
#define WATCH_LCD_RST_GPIO GPIO_NUM_8
#define WATCH_LCD_SCLK_GPIO GPIO_NUM_11
#define WATCH_LCD_CS_GPIO GPIO_NUM_12
#define WAWTCH_LCD_DATA0_GPIO GPIO_NUM_4
#define WAWTCH_LCD_DATA1_GPIO GPIO_NUM_5
#define WAWTCH_LCD_DATA2_GPIO GPIO_NUM_6
#define WAWTCH_LCD_DATA3_GPIO GPIO_NUM_7

// Touch (FT3168)

#define WATCH_TOUCH_RST_GPIO GPIO_NUM_9
#define WATCH_TOUCH_INT_GPIO GPIO_NUM_38

// Internal peripherals I2C bus
#define WATCH_I2C_PORT I2C_NUM_0
#define WATCH_I2C_SDA_GPIO GPIO_NUM_15
#define WATCH_I2C_SCL_GPIO GPIO_NUM_14
#define WATCH_I2C_FREQ_HZ 400000

// Audio codec (ES8311)
#define WATCH_AUDIO_I2C_ADDR 0x18
#define WATCH_POWER_AMP_GPIO GPIO_NUM_46

// I2S pins for codec link
#define WATCH_I2S_BCLK_GPIO GPIO_NUM_41
#define WATCH_I2S_DIN_GPIO GPIO_NUM_40
#define WATCH_I2S_WS_GPIO GPIO_NUM_45
#define WATCH_I2S_DOUT_GPIO GPIO_NUM_42

// SD card (SDSPI)
#define WATCH_SD_HOST SPI3_HOST
#define WATCH_SD_CS_GPIO GPIO_NUM_17
#define WATCH_SD_MOSI_GPIO GPIO_NUM_1
#define WATCH_SD_SCLK_GPIO GPIO_NUM_2
#define WATCH_SD_MISO_GPIO GPIO_NUM_3

// IMU (QMI8658)
#define WATCH_IMU_I2C_ADDR_PRIMARY 0x00
#define WATCH_IMU_I2C_ADDR_ALT 0x00
#define WATCH_IMU_INT_GPIO GPIO_NUM_21
