#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "Waveshare ESP32-S3-Touch-AMOLED-2.06"
#endif

#define MICROPY_HW_MCU_NAME "ESP32-S3"

#define MICROPY_HW_I2C0_SCL (14)
#define MICROPY_HW_I2C0_SDA (15)
