PICOWARE_MICROPYTHON_DIR := $(USERMOD_DIR)/../../..
FONT_MOD_DIR := $(PICOWARE_MICROPYTHON_DIR)/font

SRC_USERMOD += $(USERMOD_DIR)/font_mp.c
SRC_USERMOD += $(USERMOD_DIR)/font8.c
SRC_USERMOD += $(USERMOD_DIR)/font12.c
SRC_USERMOD += $(USERMOD_DIR)/font16.c
SRC_USERMOD += $(USERMOD_DIR)/font20.c
SRC_USERMOD += $(USERMOD_DIR)/font24.c

CFLAGS_USERMOD += -I$(FONT_MOD_DIR)
