PICOWARE_DESKTOP_DIR := $(USERMOD_DIR)/../..
PICOWARE_MICROPYTHON_DIR := $(PICOWARE_DESKTOP_DIR)/..
MMBASIC_MOD_DIR := $(PICOWARE_MICROPYTHON_DIR)/mmbasic

SRC_USERMOD += $(USERMOD_DIR)/mmbasic_mp.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_builtins.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_console.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_gfx.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_interp.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_lexer.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_nodes.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_num.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_parser.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_rnd.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_runtime.c
SRC_USERMOD += $(USERMOD_DIR)/mbs_util.c

CFLAGS_USERMOD += -I$(PICOWARE_DESKTOP_DIR)
CFLAGS_USERMOD += -I$(MMBASIC_MOD_DIR)
CFLAGS_USERMOD += -I$(MMBASIC_MOD_DIR)/lib
