MCU_SERIES = wb
CMSIS_MCU = STM32WB55xx
AF_FILE = boards/stm32wb55_af.csv
STARTUP_FILE = $(STM32LIB_CMSIS_BASE)/Source/Templates/gcc/startup_stm32wb55xx_cm4.o

LD_FILES = $(BOARD_DIR)/flipper_zero.ld boards/common_basic.ld
TEXT0_ADDR = 0x08000000

FROZEN_MANIFEST = $(BOARD_DIR)/manifest.py

MICROPY_PY_BLUETOOTH = 0
MICROPY_BLUETOOTH_NIMBLE = 0
MICROPY_VFS_LFS2 = 1
MICROPY_VFS_FAT = 1
MICROPY_HW_ENABLE_ISR_UART_FLASH_FUNCS_IN_RAM = 0
