FLIPPER_BATTERY_MOD_DIR := $(USERMOD_DIR)/battery

SRC_USERMOD += $(FLIPPER_BATTERY_MOD_DIR)/battery.c
SRC_USERMOD += $(FLIPPER_BATTERY_MOD_DIR)/battery_mp.c

CFLAGS_USERMOD += -I$(FLIPPER_BATTERY_MOD_DIR)
CFLAGS_USERMOD += -I$(USERMOD_DIR)
CFLAGS_USERMOD += -DFLIPPER_ZERO
