// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// qspi_4wire_write //
// ---------------- //

#define qspi_4wire_write_wrap_target 0
#define qspi_4wire_write_wrap 1
#define qspi_4wire_write_pio_version 0

static const uint16_t qspi_4wire_write_program_instructions[] = {
            //     .wrap_target
    0x7004, //  0: out    pins, 4         side 0
    0xb842, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program qspi_4wire_write_program = {
    .instructions = qspi_4wire_write_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = qspi_4wire_write_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config qspi_4wire_write_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + qspi_4wire_write_wrap_target, offset + qspi_4wire_write_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// ------------- //
// qspi_psram_rw //
// ------------- //

#define qspi_psram_rw_wrap_target 0
#define qspi_psram_rw_wrap 10
#define qspi_psram_rw_pio_version 0

static const uint16_t qspi_psram_rw_program_instructions[] = {
            //     .wrap_target
    0x6828, //  0: out    x, 8            side 1
    0x6848, //  1: out    y, 8            side 1
    0x0043, //  2: jmp    x--, 3          side 0
    0x6004, //  3: out    pins, 4         side 0
    0x1043, //  4: jmp    x--, 3          side 2
    0x0060, //  5: jmp    !y, 0           side 0
    0xf080, //  6: set    pindirs, 0      side 2
    0x0009, //  7: jmp    9               side 0
    0x4004, //  8: in     pins, 4         side 0
    0x1088, //  9: jmp    y--, 8          side 2
    0xe88f, // 10: set    pindirs, 15     side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program qspi_psram_rw_program = {
    .instructions = qspi_psram_rw_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = qspi_psram_rw_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config qspi_psram_rw_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + qspi_psram_rw_wrap_target, offset + qspi_psram_rw_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

// --------------- //
// spi_psram_1wire //
// --------------- //

#define spi_psram_1wire_wrap_target 0
#define spi_psram_1wire_wrap 8
#define spi_psram_1wire_pio_version 0

static const uint16_t spi_psram_1wire_program_instructions[] = {
            //     .wrap_target
    0x6828, //  0: out    x, 8            side 1
    0x6848, //  1: out    y, 8            side 1
    0x0843, //  2: jmp    x--, 3          side 1
    0x6001, //  3: out    pins, 1         side 0
    0x1043, //  4: jmp    x--, 3          side 2
    0x0060, //  5: jmp    !y, 0           side 0
    0x1008, //  6: jmp    8               side 2
    0x5001, //  7: in     pins, 1         side 2
    0x0087, //  8: jmp    y--, 7          side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spi_psram_1wire_program = {
    .instructions = spi_psram_1wire_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = spi_psram_1wire_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config spi_psram_1wire_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spi_psram_1wire_wrap_target, offset + spi_psram_1wire_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
/**
 * Initialize the QSPI 4-wire write-only program 
 * Used for fast bulk data transfers
 */
static inline void qspi_4wire_write_program_init(PIO pio, uint sm, uint offset, 
                                                  uint pin_sck, uint pin_sio0) {
    pio_sm_config c = qspi_4wire_write_program_get_default_config(offset);
    // Clock pin (sideset)
    pio_gpio_init(pio, pin_sck);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_sck, 1, true);
    sm_config_set_sideset_pins(&c, pin_sck);
    // Data pins SIO0-3 (4 consecutive pins)
    for (uint i = 0; i < 4; i++) {
        pio_gpio_init(pio, pin_sio0 + i);
    }
    pio_sm_set_consecutive_pindirs(pio, sm, pin_sio0, 4, true);
    sm_config_set_out_pins(&c, pin_sio0, 4);
    // Output shift: MSB first, autopull at 8 bits
    sm_config_set_out_shift(&c, false, true, 8);
    // Clock divider (2.0 for stability, can be lowered for speed)
    sm_config_set_clkdiv(&c, 2.0f);
    // Initialize and enable
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_clear_fifos(pio, sm);
    pio_sm_set_enabled(pio, sm, true);
}
/**
 * Initialize the QSPI bidirectional program for PSRAM
 * Supports both read and write with automatic direction switching
 */
static inline void qspi_psram_rw_program_init(PIO pio, uint sm, uint offset,
                                               uint n_bits, float clkdiv,
                                               uint pin_cs, uint pin_sio0) {
    pio_sm_config c = qspi_psram_rw_program_get_default_config(offset);
    // Data pins SIO0-3 (output and input)
    sm_config_set_out_pins(&c, pin_sio0, 4);
    sm_config_set_in_pins(&c, pin_sio0);
    sm_config_set_set_pins(&c, pin_sio0, 4);
    // CS and SCK as sideset (CS = pin_cs, SCK = pin_cs + 1)
    sm_config_set_sideset_pins(&c, pin_cs);
    // Shift configuration
    sm_config_set_out_shift(&c, false, true, n_bits);  // MSB first, autopull
    sm_config_set_in_shift(&c, false, true, n_bits);   // MSB first, autopush
    // Clock divider
    sm_config_set_clkdiv(&c, clkdiv);
    // Pin directions: CS and SCK always output
    pio_sm_set_consecutive_pindirs(pio, sm, pin_cs, 2, true);
    // SIO0-3 start as outputs
    pio_sm_set_consecutive_pindirs(pio, sm, pin_sio0, 4, true);
    // Initialize GPIO for PIO control
    pio_gpio_init(pio, pin_cs);
    pio_gpio_init(pio, pin_cs + 1);  // SCK
    for (uint i = 0; i < 4; i++) {
        pio_gpio_init(pio, pin_sio0 + i);
    }
    // Bypass input synchronizer for faster reads
    hw_set_bits(&pio->input_sync_bypass, 0xFu << pin_sio0);
    // Initialize and enable state machine
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
/**
 * Initialize the SPI 1-wire fallback program
 */
static inline void spi_psram_1wire_program_init(PIO pio, uint sm, uint offset,
                                                 uint n_bits, float clkdiv,
                                                 uint pin_cs, uint pin_mosi, uint pin_miso) {
    pio_sm_config c = spi_psram_1wire_program_get_default_config(offset);
    // MOSI (output)
    sm_config_set_out_pins(&c, pin_mosi, 1);
    // MISO (input)  
    sm_config_set_in_pins(&c, pin_miso);
    // CS and SCK as sideset
    sm_config_set_sideset_pins(&c, pin_cs);
    // Shift configuration
    sm_config_set_out_shift(&c, false, true, n_bits);
    sm_config_set_in_shift(&c, false, true, n_bits);
    // Clock divider
    sm_config_set_clkdiv(&c, clkdiv);
    // Pin directions
    pio_sm_set_consecutive_pindirs(pio, sm, pin_cs, 2, true);   // CS, SCK output
    pio_sm_set_consecutive_pindirs(pio, sm, pin_mosi, 1, true); // MOSI output
    pio_sm_set_consecutive_pindirs(pio, sm, pin_miso, 1, false); // MISO input
    // Initialize GPIO
    pio_gpio_init(pio, pin_cs);
    pio_gpio_init(pio, pin_cs + 1);
    pio_gpio_init(pio, pin_mosi);
    pio_gpio_init(pio, pin_miso);
    // Bypass input synchronizer
    hw_set_bits(&pio->input_sync_bypass, 1u << pin_miso);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

